databases:
  - name: mysitedb
    plan: free
    databaseName: 任意の名前
    user: 任意の名前

services:
  - type: web
    plan: free
    name: 任意の名前
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn bookproject.asgi:application -k uvicorn.workers.uvicornWorker"
    envVars:
      - key: DATABASE_URL
        from Database:
          name: mysitedb
          property: connectionString
      - key: WEB_CONCURRENCY
        value: 4